global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'react_frontend'
    static_configs:
      - targets: ['react_frontend:5173']
  - job_name: 'user_management_service'
    static_configs:
      - targets: ['user_management_service:8000']
  - job_name: 'data_processing_service'
    static_configs:
      - targets: ['data_processing_service:8001']