# The API version for the provisioning configuration
apiVersion: 1

# List of data sources to be provisioned
datasources:
  - name: Prometheus # The name of the data source
    type: prometheus # The type of the data source
    access: proxy # The access mode (proxy means Grafana will proxy requests to the data source)
    url: http://prometheus:9090 # The URL of the Prometheus server
    isDefault: true # Whether this data source should be the default
    editable: true # Whether this data source can be edited in the Grafana UI